### ISSUE TITLE
Timezone Conversion: Failed to respond

### ISSUE THREAD

**Issue by MaxManus** [Jwiggiff/Flow-Launcher-Timezone-Conversion-Plugin#4]
All of a sudden I got this error after typing "tz" command in FlowLauncher
"Timezone Conversion: Failed to respond!"

Flow Launcher version: 1.18.0
OS Version: 22631.3593
IntPtr Length: 8
x64: True

Python Path: C:\Users\jjx\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: C:\Users\jjx\AppData\Roaming\FlowLauncher\Environments\Node.js\Node-v16.18.0\node-v16.18.0-win-x64\node.exe
Date: 05/18/2024 09:38:21
Exception:
Timezone Conversion Exception: 
Websites: https://github.com/Jwiggiff/Flow-Launcher-Timezone-Conversion-Plugin
Author: Josh Friedman
Version: 1.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: C:\Users\jjx\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.0.0\node_modules\ms\index.js:34
  throw new Error(
  ^

Error: val is not a non-empty string or a valid number. val=""
    at module.exports (C:\Users\jjx\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.0.0\node_modules\ms\index.js:34:9)
    at Flow.<anonymous> (C:\Users\jjx\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.0.0\dist\main.js:56:80)
    at Flow.run (C:\Users\jjx\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.0.0\dist\lib\flow.js:147:75)
    at Object.<anonymous> (C:\Users\jjx\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.0.0\dist\main.js:82:6)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47

 ---> System.IO.InvalidDataException: C:\Users\jjx\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.0.0\node_modules\ms\index.js:34
  throw new Error(
  ^

Error: val is not a non-empty string or a valid number. val=""
    at module.exports (C:\Users\jjx\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.0.0\node_modules\ms\index.js:34:9)
    at Flow.<anonymous> (C:\Users\jjx\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.0.0\dist\main.js:56:80)
    at Flow.run (C:\Users\jjx\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.0.0\dist\lib\flow.js:147:75)
    at Object.<anonymous> (C:\Users\jjx\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.0.0\dist\main.js:82:6)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 249
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 249
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 264
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 196
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 230
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 224
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 307
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by deefrawley** [comment]
I get the same but I did change the default timezones (just by guessing Country/City) so might not be the same issue if the OP used the default values. It might be worthwhile putting some help text in the settings as to where users can find valid timezone strings, or verify these on keyword trigger and let the user know a timezone string is invalid.
