### ISSUE TITLE
Typing after `tz` produces error

### ISSUE THREAD

**Issue by kuphg** [Jwiggiff/Flow-Launcher-Timezone-Conversion-Plugin#6]
I'm confused as to how this plugin is supposed to function.
If i type any string after the tz command, it produces this same error.
I didn't change any config, it's all default

```Flow Launcher version: 1.16.1
OS Version: 22631.3593
IntPtr Length: 8
x64: True

Python Path: C:\Users\logic\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 05/29/2024 21:11:20
Exception:
Timezone Conversion Exception: 
Websites: https://github.com/Jwiggiff/Flow-Launcher-Timezone-Conversion-Plugin
Author: Josh Friedman
Version: 1.1.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: C:\Users\logic\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.1.0\dist\main.js:56
        date = moment_timezone_1.default.tz(timestamp[0].date(), INPUT_TZ);
                                                         ^

TypeError: Cannot read properties of undefined (reading 'date')
    at Flow.<anonymous> (C:\Users\logic\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.1.0\dist\main.js:56:58)
    at Flow.run (C:\Users\logic\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.1.0\dist\lib\flow.js:147:75)
    at Object.<anonymous> (C:\Users\logic\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.1.0\dist\main.js:95:6)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.17.1

 ---> System.IO.InvalidDataException: C:\Users\logic\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.1.0\dist\main.js:56
        date = moment_timezone_1.default.tz(timestamp[0].date(), INPUT_TZ);
                                                         ^

TypeError: Cannot read properties of undefined (reading 'date')
    at Flow.<anonymous> (C:\Users\logic\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.1.0\dist\main.js:56:58)
    at Flow.run (C:\Users\logic\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.1.0\dist\lib\flow.js:147:75)
    at Object.<anonymous> (C:\Users\logic\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.1.0\dist\main.js:95:6)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.17.1

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 291
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 296
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 311
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 193
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 839
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 813
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by guyman20** [comment]
Same here


Flow Launcher version: 1.18.0
OS Version: 19045.4651
IntPtr Length: 8
x64: True

Python Path: C:\Python\Python3.12\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 07/23/2024 13:42:39
Exception:
Timezone Conversion Exception: 
Websites: https://github.com/Jwiggiff/Flow-Launcher-Timezone-Conversion-Plugin
Author: Josh Friedman
Version: 1.1.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: C:\Users\Guy\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.1.0\dist\main.js:82
            title: date.format("h:mm a"),
                        ^

TypeError: date.format is not a function
    at C:\Users\Guy\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.1.0\dist\main.js:82:25
    at Array.map (<anonymous>)
    at getResults (C:\Users\Guy\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.1.0\dist\main.js:79:21)
    at Flow.<anonymous> (C:\Users\Guy\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.1.0\dist\main.js:62:28)
    at Flow.run (C:\Users\Guy\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.1.0\dist\lib\flow.js:147:75)
    at Object.<anonymous> (C:\Users\Guy\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.1.0\dist\main.js:95:6)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)

 ---> System.IO.InvalidDataException: C:\Users\Guy\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.1.0\dist\main.js:82
            title: date.format("h:mm a"),
                        ^

TypeError: date.format is not a function
    at C:\Users\Guy\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.1.0\dist\main.js:82:25
    at Array.map (<anonymous>)
    at getResults (C:\Users\Guy\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.1.0\dist\main.js:79:21)
    at Flow.<anonymous> (C:\Users\Guy\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.1.0\dist\main.js:62:28)
    at Flow.run (C:\Users\Guy\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.1.0\dist\lib\flow.js:147:75)
    at Object.<anonymous> (C:\Users\Guy\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.1.0\dist\main.js:95:6)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 243
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 248
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 261
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 196
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 230
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 224
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 307
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
